### ISSUE TITLE
Two issues I wanted to report

### ISSUE THREAD

**Issue by Luxac** [EnderMediaDev/The-1.7.10-Pack#886]
Hi, while I was playing the pack I noticed some things that aren't in place:

1.
The Forge Hammer is bugged (which permits infinite uses of it) as you can see from the uses (however the item for cutting into wires works fine)

![2015-09-26_17 09 51](https://cloud.githubusercontent.com/assets/14847412/10120259/e639edc6-64b2-11e5-8761-571067d49ed0.png)

2. (Not really a big issue, but I wanted to report it anyway)
There seems to be some problems with the EU meter (You can see the EU in the generator but not in other machines)
![2015-09-26_09 50 56](https://cloud.githubusercontent.com/assets/14847412/10120266/3918bb58-64b3-11e5-9e08-93bc92da1dec.png)
![2015-09-26_09 51 03](https://cloud.githubusercontent.com/assets/14847412/10120268/3fbd79d0-64b3-11e5-85db-d37367d97da2.png)
![2015-09-26_09 51 06](https://cloud.githubusercontent.com/assets/14847412/10120280/ae058edc-64b3-11e5-9f8f-3db91c858e9c.png)

**Comment by xJon** [comment]
First issue is an IC2 bug, which should already be fixed in its latest builds. If not, you can report it yourself [there](http://bt.industrial-craft.net/).
Second issue is Waila related, that you can also report [there](http://bt.industrial-craft.net/).
Both issues are very minor and they're mod-issues, so there's not much we can do about them.
Thanks anyway for reporting! :)
