### ISSUE TITLE
Client crashes when entering the server

### ISSUE THREAD

**Issue by thebalck** [EnderMediaDev/The-1.7.10-Pack#991]
Hi my game crashes when i try to enter my server, it was all ok and it crashes from the air since yesterday idk why, yes i have added some mods but the crash was like days after that 
can you help me plz, i think its a something in the render of the game that is bugging because only client crashes
[crash-2016-01-19_15.10.59-client.txt](https://github.com/EnderMediaDev/The-1.7.10-Pack/files/96099/crash-2016-01-19_15.10.59-client.txt)

EDIT:. I downloaded the world and i tested in Single Player and i crash again, so this is not server side, ill try to delete all my client files and download the game again 

Update:. After download the pack again the crash continues,maybe the world file is corrupted because is only in that chunk that i crash, ill download a old version of the world and test again

**Comment by xJon** [comment]
The error is related to the VoxelMap mod.
Unfortunately, due to the addition of mods, I can't really help you.
I can direct you to the [VoxelMap](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2261180) thread in the Mincreaft Forums, which there you can ask for help, including your crash report.

**Comment by thebalck** [comment]
Ok thank you
