### ISSUE TITLE
Crash on opening a specific chest

### ISSUE THREAD

**Issue by Ocrilat** [EnderMediaDev/The-1.7.10-Pack#999]
After the most recent update...if I try to open one particular chest, my game crashes. No crashes otherwise at all. Now, the chest was one that I would throw 'oddities' into, so I was curious if anyone else had this problem...and if there is a workaround or a fix. Oddly enough, the other player on the server has the same issue, with one chest.

**Comment by xJon** [comment]
Crash report? please use a paste-tool.

**Comment by Ocrilat** [comment]
It doesn't say anything at all...simply crashes to the technic launcher. Or is there a way to get a report manually?

**Comment by xJon** [comment]
Please read [this](https://github.com/EnderMediaDev/The-1.7.10-Pack/blob/master/README.md).

**Comment by Ocrilat** [comment]
Thanks...I double check and get back to you!

**Comment by Mistercris** [comment]
Hate to poke in, but did you have any Rock bee's(or extra bee mod stuff) situated inside said chests?
I believe that might be your problem, this log http://pastebin.com/9fcMqmHE shows the problem with extra bee's.

Due to being a world getting a upgrade and not a fresh start, there was still something lingering from the extra bee mod, and the fix (See config option "genetics.clear.invalid.chromosomes") wasnt working correctly for me (that or I was not using it correctly).

So I deleted all things extra bee related in said chests with NBTE.
Let me know if deleting the extra bee lingering content works

**Comment by xJon** [comment]
Closed due to missing information.
